#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AlquilerLibros")]
	public partial class DBAlquilerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAutor(Autor instance);
    partial void UpdateAutor(Autor instance);
    partial void DeleteAutor(Autor instance);
    partial void InsertAutorLibro(AutorLibro instance);
    partial void UpdateAutorLibro(AutorLibro instance);
    partial void DeleteAutorLibro(AutorLibro instance);
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertEditorial(Editorial instance);
    partial void UpdateEditorial(Editorial instance);
    partial void DeleteEditorial(Editorial instance);
    partial void InsertEstudiante(Estudiante instance);
    partial void UpdateEstudiante(Estudiante instance);
    partial void DeleteEstudiante(Estudiante instance);
    partial void InsertLibro(Libro instance);
    partial void UpdateLibro(Libro instance);
    partial void DeleteLibro(Libro instance);
    partial void InsertPrestamo(Prestamo instance);
    partial void UpdatePrestamo(Prestamo instance);
    partial void DeletePrestamo(Prestamo instance);
    #endregion
		
		public DBAlquilerDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.AlquilerLibrosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBAlquilerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBAlquilerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBAlquilerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBAlquilerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Autor> Autor
		{
			get
			{
				return this.GetTable<Autor>();
			}
		}
		
		public System.Data.Linq.Table<AutorLibro> AutorLibro
		{
			get
			{
				return this.GetTable<AutorLibro>();
			}
		}
		
		public System.Data.Linq.Table<Categoria> Categoria
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Editorial> Editorial
		{
			get
			{
				return this.GetTable<Editorial>();
			}
		}
		
		public System.Data.Linq.Table<Estudiante> Estudiante
		{
			get
			{
				return this.GetTable<Estudiante>();
			}
		}
		
		public System.Data.Linq.Table<Libro> Libro
		{
			get
			{
				return this.GetTable<Libro>();
			}
		}
		
		public System.Data.Linq.Table<Prestamo> Prestamo
		{
			get
			{
				return this.GetTable<Prestamo>();
			}
		}
		
		public System.Data.Linq.Table<PrestamoLibro> PrestamoLibro
		{
			get
			{
				return this.GetTable<PrestamoLibro>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarAutor")]
		public ISingleResult<CP_ListarAutorResult> CP_ListarAutor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string val)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), val);
			return ((ISingleResult<CP_ListarAutorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminararAutor")]
		public int CP_EliminararAutor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarAutor")]
		public int CP_InsertarAutor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string est, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string ape, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> sex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fec)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, est, nom, ape, sex, fec);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ModificarAutor")]
		public int CP_ModificarAutor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string est, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string ape, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> sex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fec)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, est, nom, ape, sex, fec);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Autor")]
	public partial class Autor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_autor;
		
		private string _estado;
		
		private string _nombre;
		
		private string _apellido;
		
		private char _sexo;
		
		private System.DateTime _fecha_nacimiento;
		
		private EntitySet<AutorLibro> _AutorLibro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_autorChanging(int value);
    partial void Onid_autorChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnsexoChanging(char value);
    partial void OnsexoChanged();
    partial void Onfecha_nacimientoChanging(System.DateTime value);
    partial void Onfecha_nacimientoChanged();
    #endregion
		
		public Autor()
		{
			this._AutorLibro = new EntitySet<AutorLibro>(new Action<AutorLibro>(this.attach_AutorLibro), new Action<AutorLibro>(this.detach_AutorLibro));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_autor", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_autor
		{
			get
			{
				return this._id_autor;
			}
			set
			{
				if ((this._id_autor != value))
				{
					this.Onid_autorChanging(value);
					this.SendPropertyChanging();
					this._id_autor = value;
					this.SendPropertyChanged("id_autor");
					this.Onid_autorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(25)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(1) NOT NULL")]
		public char sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Autor_AutorLibro", Storage="_AutorLibro", ThisKey="id_autor", OtherKey="id_autor")]
		public EntitySet<AutorLibro> AutorLibro
		{
			get
			{
				return this._AutorLibro;
			}
			set
			{
				this._AutorLibro.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AutorLibro(AutorLibro entity)
		{
			this.SendPropertyChanging();
			entity.Autor = this;
		}
		
		private void detach_AutorLibro(AutorLibro entity)
		{
			this.SendPropertyChanging();
			entity.Autor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AutorLibro")]
	public partial class AutorLibro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_autor;
		
		private int _id_libro;
		
		private EntityRef<Autor> _Autor;
		
		private EntityRef<Libro> _Libro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_autorChanging(int value);
    partial void Onid_autorChanged();
    partial void Onid_libroChanging(int value);
    partial void Onid_libroChanged();
    #endregion
		
		public AutorLibro()
		{
			this._Autor = default(EntityRef<Autor>);
			this._Libro = default(EntityRef<Libro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_autor", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_autor
		{
			get
			{
				return this._id_autor;
			}
			set
			{
				if ((this._id_autor != value))
				{
					if (this._Autor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_autorChanging(value);
					this.SendPropertyChanging();
					this._id_autor = value;
					this.SendPropertyChanged("id_autor");
					this.Onid_autorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_libro", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_libro
		{
			get
			{
				return this._id_libro;
			}
			set
			{
				if ((this._id_libro != value))
				{
					if (this._Libro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_libroChanging(value);
					this.SendPropertyChanging();
					this._id_libro = value;
					this.SendPropertyChanged("id_libro");
					this.Onid_libroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Autor_AutorLibro", Storage="_Autor", ThisKey="id_autor", OtherKey="id_autor", IsForeignKey=true)]
		public Autor Autor
		{
			get
			{
				return this._Autor.Entity;
			}
			set
			{
				Autor previousValue = this._Autor.Entity;
				if (((previousValue != value) 
							|| (this._Autor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Autor.Entity = null;
						previousValue.AutorLibro.Remove(this);
					}
					this._Autor.Entity = value;
					if ((value != null))
					{
						value.AutorLibro.Add(this);
						this._id_autor = value.id_autor;
					}
					else
					{
						this._id_autor = default(int);
					}
					this.SendPropertyChanged("Autor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Libro_AutorLibro", Storage="_Libro", ThisKey="id_libro", OtherKey="id_libro", IsForeignKey=true)]
		public Libro Libro
		{
			get
			{
				return this._Libro.Entity;
			}
			set
			{
				Libro previousValue = this._Libro.Entity;
				if (((previousValue != value) 
							|| (this._Libro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Libro.Entity = null;
						previousValue.AutorLibro.Remove(this);
					}
					this._Libro.Entity = value;
					if ((value != null))
					{
						value.AutorLibro.Add(this);
						this._id_libro = value.id_libro;
					}
					else
					{
						this._id_libro = default(int);
					}
					this.SendPropertyChanged("Libro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categoria")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categoria;
		
		private string _nombre;
		
		private string _descripcion;
		
		private EntitySet<Libro> _Libro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public Categoria()
		{
			this._Libro = new EntitySet<Libro>(new Action<Libro>(this.attach_Libro), new Action<Libro>(this.detach_Libro));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Libro", Storage="_Libro", ThisKey="id_categoria", OtherKey="id_categoria")]
		public EntitySet<Libro> Libro
		{
			get
			{
				return this._Libro;
			}
			set
			{
				this._Libro.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Libro(Libro entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Libro(Libro entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Editorial")]
	public partial class Editorial : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_editorial;
		
		private string _nombre;
		
		private string _pais;
		
		private EntitySet<Libro> _Libro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_editorialChanging(int value);
    partial void Onid_editorialChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnpaisChanging(string value);
    partial void OnpaisChanged();
    #endregion
		
		public Editorial()
		{
			this._Libro = new EntitySet<Libro>(new Action<Libro>(this.attach_Libro), new Action<Libro>(this.detach_Libro));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_editorial", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_editorial
		{
			get
			{
				return this._id_editorial;
			}
			set
			{
				if ((this._id_editorial != value))
				{
					this.Onid_editorialChanging(value);
					this.SendPropertyChanging();
					this._id_editorial = value;
					this.SendPropertyChanged("id_editorial");
					this.Onid_editorialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pais", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string pais
		{
			get
			{
				return this._pais;
			}
			set
			{
				if ((this._pais != value))
				{
					this.OnpaisChanging(value);
					this.SendPropertyChanging();
					this._pais = value;
					this.SendPropertyChanged("pais");
					this.OnpaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Editorial_Libro", Storage="_Libro", ThisKey="id_editorial", OtherKey="id_editorial")]
		public EntitySet<Libro> Libro
		{
			get
			{
				return this._Libro;
			}
			set
			{
				this._Libro.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Libro(Libro entity)
		{
			this.SendPropertyChanging();
			entity.Editorial = this;
		}
		
		private void detach_Libro(Libro entity)
		{
			this.SendPropertyChanging();
			entity.Editorial = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estudiante")]
	public partial class Estudiante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_estudiante;
		
		private string _cedula;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _sexo;
		
		private System.DateTime _fecha_nacimiento;
		
		private string _estadocivil;
		
		private string _estado;
		
		private EntitySet<Prestamo> _Prestamo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_estudianteChanging(int value);
    partial void Onid_estudianteChanged();
    partial void OncedulaChanging(string value);
    partial void OncedulaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void Onfecha_nacimientoChanging(System.DateTime value);
    partial void Onfecha_nacimientoChanged();
    partial void OnestadocivilChanging(string value);
    partial void OnestadocivilChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public Estudiante()
		{
			this._Prestamo = new EntitySet<Prestamo>(new Action<Prestamo>(this.attach_Prestamo), new Action<Prestamo>(this.detach_Prestamo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estudiante", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_estudiante
		{
			get
			{
				return this._id_estudiante;
			}
			set
			{
				if ((this._id_estudiante != value))
				{
					this.Onid_estudianteChanging(value);
					this.SendPropertyChanging();
					this._id_estudiante = value;
					this.SendPropertyChanged("id_estudiante");
					this.Onid_estudianteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this.OncedulaChanging(value);
					this.SendPropertyChanging();
					this._cedula = value;
					this.SendPropertyChanged("cedula");
					this.OncedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadocivil", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string estadocivil
		{
			get
			{
				return this._estadocivil;
			}
			set
			{
				if ((this._estadocivil != value))
				{
					this.OnestadocivilChanging(value);
					this.SendPropertyChanging();
					this._estadocivil = value;
					this.SendPropertyChanged("estadocivil");
					this.OnestadocivilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Char(25)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estudiante_Prestamo", Storage="_Prestamo", ThisKey="id_estudiante", OtherKey="id_estudiante")]
		public EntitySet<Prestamo> Prestamo
		{
			get
			{
				return this._Prestamo;
			}
			set
			{
				this._Prestamo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Prestamo(Prestamo entity)
		{
			this.SendPropertyChanging();
			entity.Estudiante = this;
		}
		
		private void detach_Prestamo(Prestamo entity)
		{
			this.SendPropertyChanging();
			entity.Estudiante = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Libro")]
	public partial class Libro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_libro;
		
		private System.DateTime _anio_publicacion;
		
		private string _tipo;
		
		private string _nombre;
		
		private string _disponibilidad;
		
		private int _id_editorial;
		
		private int _id_categoria;
		
		private EntitySet<AutorLibro> _AutorLibro;
		
		private EntityRef<Categoria> _Categoria;
		
		private EntityRef<Editorial> _Editorial;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_libroChanging(int value);
    partial void Onid_libroChanged();
    partial void Onanio_publicacionChanging(System.DateTime value);
    partial void Onanio_publicacionChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndisponibilidadChanging(string value);
    partial void OndisponibilidadChanged();
    partial void Onid_editorialChanging(int value);
    partial void Onid_editorialChanged();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    #endregion
		
		public Libro()
		{
			this._AutorLibro = new EntitySet<AutorLibro>(new Action<AutorLibro>(this.attach_AutorLibro), new Action<AutorLibro>(this.detach_AutorLibro));
			this._Categoria = default(EntityRef<Categoria>);
			this._Editorial = default(EntityRef<Editorial>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_libro", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_libro
		{
			get
			{
				return this._id_libro;
			}
			set
			{
				if ((this._id_libro != value))
				{
					this.Onid_libroChanging(value);
					this.SendPropertyChanging();
					this._id_libro = value;
					this.SendPropertyChanged("id_libro");
					this.Onid_libroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anio_publicacion", DbType="DateTime NOT NULL")]
		public System.DateTime anio_publicacion
		{
			get
			{
				return this._anio_publicacion;
			}
			set
			{
				if ((this._anio_publicacion != value))
				{
					this.Onanio_publicacionChanging(value);
					this.SendPropertyChanging();
					this._anio_publicacion = value;
					this.SendPropertyChanged("anio_publicacion");
					this.Onanio_publicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disponibilidad", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string disponibilidad
		{
			get
			{
				return this._disponibilidad;
			}
			set
			{
				if ((this._disponibilidad != value))
				{
					this.OndisponibilidadChanging(value);
					this.SendPropertyChanging();
					this._disponibilidad = value;
					this.SendPropertyChanged("disponibilidad");
					this.OndisponibilidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_editorial", DbType="Int NOT NULL")]
		public int id_editorial
		{
			get
			{
				return this._id_editorial;
			}
			set
			{
				if ((this._id_editorial != value))
				{
					if (this._Editorial.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_editorialChanging(value);
					this.SendPropertyChanging();
					this._id_editorial = value;
					this.SendPropertyChanged("id_editorial");
					this.Onid_editorialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int NOT NULL")]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					if (this._Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Libro_AutorLibro", Storage="_AutorLibro", ThisKey="id_libro", OtherKey="id_libro")]
		public EntitySet<AutorLibro> AutorLibro
		{
			get
			{
				return this._AutorLibro;
			}
			set
			{
				this._AutorLibro.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Libro", Storage="_Categoria", ThisKey="id_categoria", OtherKey="id_categoria", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Libro.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Libro.Add(this);
						this._id_categoria = value.id_categoria;
					}
					else
					{
						this._id_categoria = default(int);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Editorial_Libro", Storage="_Editorial", ThisKey="id_editorial", OtherKey="id_editorial", IsForeignKey=true)]
		public Editorial Editorial
		{
			get
			{
				return this._Editorial.Entity;
			}
			set
			{
				Editorial previousValue = this._Editorial.Entity;
				if (((previousValue != value) 
							|| (this._Editorial.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Editorial.Entity = null;
						previousValue.Libro.Remove(this);
					}
					this._Editorial.Entity = value;
					if ((value != null))
					{
						value.Libro.Add(this);
						this._id_editorial = value.id_editorial;
					}
					else
					{
						this._id_editorial = default(int);
					}
					this.SendPropertyChanged("Editorial");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AutorLibro(AutorLibro entity)
		{
			this.SendPropertyChanging();
			entity.Libro = this;
		}
		
		private void detach_AutorLibro(AutorLibro entity)
		{
			this.SendPropertyChanging();
			entity.Libro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prestamo")]
	public partial class Prestamo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_prestamo;
		
		private System.DateTime _fecha_entraga;
		
		private System.Nullable<System.DateTime> _fecha_tentativa;
		
		private System.DateTime _fecha_prestamo;
		
		private string _estado;
		
		private int _id_estudiante;
		
		private EntityRef<Estudiante> _Estudiante;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_prestamoChanging(int value);
    partial void Onid_prestamoChanged();
    partial void Onfecha_entragaChanging(System.DateTime value);
    partial void Onfecha_entragaChanged();
    partial void Onfecha_tentativaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_tentativaChanged();
    partial void Onfecha_prestamoChanging(System.DateTime value);
    partial void Onfecha_prestamoChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void Onid_estudianteChanging(int value);
    partial void Onid_estudianteChanged();
    #endregion
		
		public Prestamo()
		{
			this._Estudiante = default(EntityRef<Estudiante>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_prestamo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_prestamo
		{
			get
			{
				return this._id_prestamo;
			}
			set
			{
				if ((this._id_prestamo != value))
				{
					this.Onid_prestamoChanging(value);
					this.SendPropertyChanging();
					this._id_prestamo = value;
					this.SendPropertyChanged("id_prestamo");
					this.Onid_prestamoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_entraga", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_entraga
		{
			get
			{
				return this._fecha_entraga;
			}
			set
			{
				if ((this._fecha_entraga != value))
				{
					this.Onfecha_entragaChanging(value);
					this.SendPropertyChanging();
					this._fecha_entraga = value;
					this.SendPropertyChanged("fecha_entraga");
					this.Onfecha_entragaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_tentativa", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_tentativa
		{
			get
			{
				return this._fecha_tentativa;
			}
			set
			{
				if ((this._fecha_tentativa != value))
				{
					this.Onfecha_tentativaChanging(value);
					this.SendPropertyChanging();
					this._fecha_tentativa = value;
					this.SendPropertyChanged("fecha_tentativa");
					this.Onfecha_tentativaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_prestamo", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_prestamo
		{
			get
			{
				return this._fecha_prestamo;
			}
			set
			{
				if ((this._fecha_prestamo != value))
				{
					this.Onfecha_prestamoChanging(value);
					this.SendPropertyChanging();
					this._fecha_prestamo = value;
					this.SendPropertyChanged("fecha_prestamo");
					this.Onfecha_prestamoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estudiante", DbType="Int NOT NULL")]
		public int id_estudiante
		{
			get
			{
				return this._id_estudiante;
			}
			set
			{
				if ((this._id_estudiante != value))
				{
					if (this._Estudiante.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_estudianteChanging(value);
					this.SendPropertyChanging();
					this._id_estudiante = value;
					this.SendPropertyChanged("id_estudiante");
					this.Onid_estudianteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estudiante_Prestamo", Storage="_Estudiante", ThisKey="id_estudiante", OtherKey="id_estudiante", IsForeignKey=true)]
		public Estudiante Estudiante
		{
			get
			{
				return this._Estudiante.Entity;
			}
			set
			{
				Estudiante previousValue = this._Estudiante.Entity;
				if (((previousValue != value) 
							|| (this._Estudiante.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estudiante.Entity = null;
						previousValue.Prestamo.Remove(this);
					}
					this._Estudiante.Entity = value;
					if ((value != null))
					{
						value.Prestamo.Add(this);
						this._id_estudiante = value.id_estudiante;
					}
					else
					{
						this._id_estudiante = default(int);
					}
					this.SendPropertyChanged("Estudiante");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PrestamoLibro")]
	public partial class PrestamoLibro
	{
		
		private System.Nullable<int> _id_prestamo;
		
		private System.Nullable<int> _id_libro;
		
		public PrestamoLibro()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_prestamo", DbType="Int")]
		public System.Nullable<int> id_prestamo
		{
			get
			{
				return this._id_prestamo;
			}
			set
			{
				if ((this._id_prestamo != value))
				{
					this._id_prestamo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_libro", DbType="Int")]
		public System.Nullable<int> id_libro
		{
			get
			{
				return this._id_libro;
			}
			set
			{
				if ((this._id_libro != value))
				{
					this._id_libro = value;
				}
			}
		}
	}
	
	public partial class CP_ListarAutorResult
	{
		
		private int _id_autor;
		
		private string _estado;
		
		private string _nombre;
		
		private string _apellido;
		
		private char _sexo;
		
		private System.DateTime _fecha_nacimiento;
		
		public CP_ListarAutorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_autor", DbType="Int NOT NULL")]
		public int id_autor
		{
			get
			{
				return this._id_autor;
			}
			set
			{
				if ((this._id_autor != value))
				{
					this._id_autor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(25)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this._apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(1) NOT NULL")]
		public char sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this._sexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this._fecha_nacimiento = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
